import pytest

from scrape.playing_roster import scrape_roster


@pytest.fixture
def game_id():
    return 2016010053


@pytest.fixture
def roster():
    return {
        'head_coaches': {
            'Away': 'MICHEL THERRIEN',
            'Home': 'GUY BOUCHER',
        },
        'players': {
            'Away': [
                ['17', 'C', 'TORREY MITCHELL'],
                ['21', 'C', 'STEFAN MATTEAU'],
                ['24', 'L', 'PHILLIP DANAULT'],
                ['25', 'L', 'JACOB DE LA ROSE'],
                ['32', 'C', 'BRIAN FLYNN'],
                ['34', 'R', 'MICHAEL MCCARRON'],
                ['36', 'D', 'BRETT LERNOUT'],
                ['38', 'R', 'NIKITA SCHERBAK'],
                ['41', 'L', 'PAUL BYRON'],
                ['44', 'R', 'BOBBY FARNHAM'],
                ['48', 'C', 'DANIEL AUDETTE'],
                ['52', 'D', 'PHILIP SAMUELSSON'],
                ['54', 'L', 'CHARLES HUDON'],
                ['58', 'D', 'NOAH JUULSEN'],
                ['63', 'C', 'JEREMY GRÉGOIRE'],
                ['75', 'D', 'YURY ALEXANDROV'],
                ['82', 'D', 'TOM PARISI'],
                ['89', 'D', 'RYAN JOHNSTON'],
                ['30', 'G', 'ZACHARY FUCALE'],
                ['35', 'G', 'AL MONTOYA'],
                ['0', 'L', 'JEREMIAH ADDISON'],
                ['0', 'R', 'GUILLAUME ASSELIN'],
                ['0', 'D', 'SIMON BOURQUE'],
                ['0', 'C', 'MATTHEW BRADLEY'],
                ['0', 'D', 'JOSIAH DIDIER'],
                ['0', 'C', 'JAKE EVANS'],
                ['0', 'D', 'NIKOLAS KOBERSTEIN'],
                ['0', 'D', 'KONSTANTIN KORNEEV'],
                ['0', 'D', 'ANDREI KRUCHININ'],
                ['0', 'L', 'MARTIN REWAY'],
                ['0', 'R', 'ANDREI SIDYAKIN'],
                ['0', 'D', 'COLIN SULLIVAN'],
                ['0', 'R', 'MAXIM TRUNEV'],
                ['0', 'C', 'LUKAS VEJDEMO'],
                ['6', 'D', 'SHEA WEBER'],
                ['8', 'D', 'GREG PATERYN'],
                ['11', 'R', 'BRENDAN GALLAGHER'],
                ['14', 'C', 'TOMAS PLEKANEC'],
                ['15', 'L', 'CHRIS TERRY'],
                ['20', 'D', 'ZACH REDMOND'],
                ['22', 'D', 'MIKHAIL SERGACHEV'],
                ['26', 'D', 'JEFF PETRY'],
                ['27', 'C', 'ALEX GALCHENYUK'],
                ['28', 'D', 'NATHAN BEAULIEU'],
                ['37', 'C', 'WILLIAM BITTEN'],
                ['40', 'L', 'CONNOR CRISP'],
                ['42', 'R', 'SVEN ANDRIGHETTO'],
                ['43', 'L', 'DANIEL CARR'],
                ['45', 'D', 'MARK BARBERIO'],
                ['46', 'L', 'ARTTURI LEHKONEN'],
                ['47', 'R', 'ALEXANDER RADULOV'],
                ['49', 'L', 'MAX FRIBERG'],
                ['49', 'D', 'CASEY STAUM'],
                ['51', 'C', 'DAVID DESHARNAIS'],
                ['53', 'D', 'VICTOR METE'],
                ['55', 'C', 'MICHAEL PEZZETTA'],
                ['56', 'L', 'TIM BOZON'],
                ['59', 'D', 'DALTON THROWER'],
                ['65', 'C', 'ANDREW SHAW'],
                ['67', 'L', 'MAX PACIORETTY'],
                ['68', 'R', 'MARK MACMILLAN'],
                ['71', 'D', 'JOEL HANLEY'],
                ['74', 'D', 'ALEXEI EMELIN'],
                ['79', 'D', 'ANDREI MARKOV'],
                ['81', 'D', 'ARVID HENRIKSON'],
                ['0', 'G', 'HAYDEN HAWKEY'],
                ['31', 'G', 'CAREY PRICE'],
                ['39', 'G', 'MIKE CONDON'],
                ['40', 'G', 'CHARLIE LINDGREN'],
                ['40', 'G', 'MICHAEL MCNIVEN']
            ],
            'Home': [
                ['2', 'D', 'DION PHANEUF'],
                ['5', 'D', 'CODY CECI'],
                ['7', 'C', 'KYLE TURRIS'],
                ['9', 'R', 'BOBBY RYAN'],
                ['10', 'C', 'TOM PYATT'],
                ['12', 'D', 'MATT BARTKOWSKI'],
                ['19', 'C', 'DERICK BRASSARD'],
                ['21', 'D', 'MICHAEL KOSTKA'],
                ['22', 'C', 'CHRIS KELLY'],
                ['25', 'R', 'CHRIS NEIL'],
                ['26', 'L', 'MATT PUEMPEL'],
                ['33', 'D', 'FREDRIK CLAESSON'],
                ['43', 'C', 'RYAN DZINGEL'],
                ['44', 'C', 'JEAN-GABRIEL PAGEAU'],
                ['65', 'D', 'ERIK KARLSSON'],
                ['68', 'C', 'MIKE HOFFMAN'],
                ['72', 'D', 'THOMAS CHABOT'],
                ['81', 'C', 'PHIL VARONE'],
                ['30', 'G', 'ANDREW HAMMOND'],
                ['32', 'G', 'CHRIS DRIEDGER'],
                ['0', 'L', 'VINCENT ARSENEAU'],
                ['0', 'D', 'VITALI ATYUSHOV'],
                ['0', 'L', 'RUSLAN BASHKIROV'],
                ['0', 'D', 'CHRIS CARLISLE'],
                ['0', 'D', 'SERGEI GIMAYEV'],
                ['0', 'D', 'GUILLAUME LEPINE'],
                ['0', 'C', 'ALEXIS LOISEAU'],
                ['0', 'D', 'KIRILL LYAMIN'],
                ['0', 'R', 'LOUICK MARCOTTE'],
                ['0', 'D', 'DIMITRI MEGALINSKY'],
                ['0', 'C', 'IGOR MIRNOV'],
                ['0', 'L', 'BRAD PELTZ'],
                ['0', 'D', 'CHRIS RUMBLE'],
                ['3', 'D', 'MARC METHOT'],
                ['6', 'D', 'CHRIS WIDEMAN'],
                ['13', 'L', 'NICK PAUL'],
                ['14', 'R', 'MIKE BLUNDEN'],
                ['15', 'C', 'ZACK SMITH'],
                ['16', 'L', 'CLARKE MACARTHUR'],
                ['23', 'C', 'CHAD NEHRING'],
                ['27', 'C', 'CURTIS LAZAR'],
                ['36', 'C', 'VINCENT DUNN'],
                ['37', 'C', 'CASEY BAILEY'],
                ['38', 'C', 'ROBERT BAILLARGEON'],
                ['47', 'D', 'TIMOTHY BOYLE'],
                ['47', 'L', 'FRANCIS PERRON'],
                ['48', 'C', 'JONATHAN DAHLEN'],
                ['50', 'D', 'PATRICK SIELOFF'],
                ['51', 'C', 'LOGAN BROWN'],
                ['52', 'R', 'MARKUS NURMI'],
                ['53', 'D', 'ANDREAS ENGLUND'],
                ['54', 'D', 'MILES GENDRON'],
                ['55', 'R', 'BUDDY ROBINSON'],
                ['56', 'R', 'ZACK STORTINI'],
                ['58', 'D', 'MAXIME LAJOIE'],
                ['59', 'C', 'KYLE FLANAGAN'],
                ['61', 'R', 'MARK STONE'],
                ['62', 'R', 'TODD BURGESS'],
                ['63', 'D', 'CODY DONAGHEY'],
                ['64', 'C', 'SHANE EISERMAN'],
                ['64', 'R', 'CHRIS LEBLANC'],
                ['65', 'L', 'ALEXANDER KRUSHELNYSKI'],
                ['66', 'R', 'JACK RODEWALD'],
                ['66', 'D', 'MIKAEL WIKSTRAND'],
                ['67', 'D', 'BEN HARPUR'],
                ['70', 'D', 'KELLY SUMMERS'],
                ['71', 'R', 'GABRIEL GAGNE'],
                ['74', 'D', 'MARK BOROWIECKI'],
                ['76', 'L', 'FILIP AHL'],
                ['78', 'C', 'FILIP CHLAPIK'],
                ['79', 'C', 'RYAN RUPERT'],
                ['80', 'D', 'MACOY ERKAMPS'],
                ['82', 'C', 'COLIN WHITE'],
                ['83', 'D', 'CHRISTIAN JAROS'],
                ['86', 'D', 'CHRISTIAN WOLANIN'],
                ['89', 'L', 'MAX MCCORMICK'],
                ['0', 'G', 'JOEL DACCORD'],
                ['0', 'G', 'SCOTT GREENHAM'],
                ['29', 'G', "MATTHEW O'CONNOR"],
                ['35', 'G', 'MARCUS HOGBERG'],
                ['41', 'G', 'CRAIG ANDERSON'],
                ['50', 'G', 'BRYAN PITTON']
            ],
        },
    }


@pytest.mark.live
def test_scrape_roster(game_id, roster):
    scraped = scrape_roster(game_id)
    assert scraped

    assert 'head_coaches' in scraped
    assert scraped['head_coaches'] == roster['head_coaches']

    assert 'players' in scraped
    assert 'Away' in scraped['players']
    assert 'Home' in scraped['players']

    assert scraped['players']['Away'] == roster['players']['Away']
    assert scraped['players']['Home'] == roster['players']['Home']
